unit uQRAuxilios;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Qrctrls, QuickRpt, ExtCtrls, Db, DBTables;

type
  TFQRAuxilios = class(TForm)
    QuickRep: TQuickRep;
    tEmpresaLogo: TTable;
    tEmpresaLogoCODIGOEMPRESA: TStringField;
    tEmpresaLogoCONSECUTIVO: TStringField;
    tEmpresaLogoLOGOEMPRESA: TBlobField;
    dsEmpresaLogo: TDataSource;
    QRBand1: TQRBand;
    QRShape21: TQRShape;
    QRShape23: TQRShape;
    QRLabel39: TQRLabel;
    QRShape24: TQRShape;
    QRLabel40: TQRLabel;
    QRShape25: TQRShape;
    QRShape26: TQRShape;
    QRShape27: TQRShape;
    QRShape28: TQRShape;
    qrdbCodigoOdt: TQRDBText;
    QRLabel41: TQRLabel;
    QRLabel42: TQRLabel;
    qrdbNombreEmpleado: TQRDBText;
    qrdbCedula: TQRDBText;
    QRShape29: TQRShape;
    QRLabel43: TQRLabel;
    QRLabel44: TQRLabel;
    QRLabel45: TQRLabel;
    QRLabel46: TQRLabel;
    QRLabel47: TQRLabel;
    QRLabel48: TQRLabel;
    QRLabel49: TQRLabel;
    QRLabel50: TQRLabel;
    QRLabel51: TQRLabel;
    qr: TQRLabel;
    qrl: TQRLabel;
    QRLabel55: TQRLabel;
    qrlDesayuno: TQRLabel;
    qrlAlmuerzo: TQRLabel;
    qrlComida: TQRLabel;
    qrdbDiaDesdeDesayuno: TQRDBText;
    qrdbDiaDesdeAlmuerzo: TQRDBText;
    qrdbDiaDesdeComida: TQRDBText;
    qrdbMesdesdeDesayuno: TQRDBText;
    qrdbMesDesdeAlmuerzo: TQRDBText;
    qrdbMesDesdeComida: TQRDBText;
    qrdbDiaHastaDesayuno: TQRDBText;
    qrdbDiaHastaAlmuerzo: TQRDBText;
    qrdbDiaHastaComida: TQRDBText;
    qrdbMesHastaDesayuno: TQRDBText;
    qrdbMesHastaAlmuerzo: TQRDBText;
    qrdbMesHastaComida: TQRDBText;
    qrdbAnhoDesayuno: TQRDBText;
    qrdbAnhoAlmuerzo: TQRDBText;
    qrdbAnhoComida: TQRDBText;
    QRLabel59: TQRLabel;
    qrlPeaje: TQRLabel;
    qrlParqueo: TQRLabel;
    qrlgasolina: TQRLabel;
    qrlPasaje: TQRLabel;
    QRLabel64: TQRLabel;
    QRLabel65: TQRLabel;
    QRLabel66: TQRLabel;
    QRLabel67: TQRLabel;
    QRLabel68: TQRLabel;
    QRLabel69: TQRLabel;
    qrdbValorPeaje: TQRDBText;
    qrdbValorParqueo: TQRDBText;
    qrdbValorGasolina: TQRDBText;
    qrdbValorPasajes: TQRDBText;
    qrdbFechaPeaje: TQRDBText;
    qrdbFechaParqueo: TQRDBText;
    qrdbFechaGasolina: TQRDBText;
    qrdbFechaPasajes: TQRDBText;
    QRLabel70: TQRLabel;
    QRShape30: TQRShape;
    QRLabel71: TQRLabel;
    QRLabel72: TQRLabel;
    QRShape31: TQRShape;
    QRShape32: TQRShape;
    QRShape33: TQRShape;
    QRShape34: TQRShape;
    QRShape35: TQRShape;
    QRLabel73: TQRLabel;
    qrdbCuentaContable: TQRDBText;
    qrdbAuxiliar: TQRDBText;
    qrdbCentroCosto: TQRDBText;
    qrdbAreaResponsabilidad: TQRDBText;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRShape38: TQRShape;
    QRLabel74: TQRLabel;
    QRLabel75: TQRLabel;
    QRLabel76: TQRLabel;
    QRShape39: TQRShape;
    QRShape40: TQRShape;
    QRShape41: TQRShape;
    QRLabel77: TQRLabel;
    QRLabel78: TQRLabel;
    qrdbFechaPago: TQRDBText;
    qrdbValorDesayuno: TQRDBText;
    qrdbValorAlmuerzo: TQRDBText;
    qrdbValorComida: TQRDBText;
    qrdbTotalAlimentacion: TQRDBText;
    qrdbTotalAuxilio: TQRDBText;
    QRLabel79: TQRLabel;
    qrdbTotalOtrosGastos: TQRDBText;
    qrdbCantidadDesayuno: TQRDBText;
    qrdbCantidadAlmuerzo: TQRDBText;
    qrdbCantidadComida: TQRDBText;
    qrdbCedulaFirma: TQRDBText;
    QRShape42: TQRShape;
    QRDBImage1: TQRDBImage;
    QRImage2: TQRImage;
    QRLabel82: TQRLabel;
    QRLabel83: TQRLabel;
    QRLabel84: TQRLabel;
    qEmpresa: TQuery;
    QRDBText2: TQRDBText;
    qrdbCia: TQRDBText;
    DetailBand1: TQRBand;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRShape5: TQRShape;
    QRShape6: TQRShape;
    QRShape7: TQRShape;
    QRShape8: TQRShape;
    qrdbCodigoOdtCopia: TQRDBText;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    qrdbNombreEmpleadoCopia: TQRDBText;
    qrdbCedulaCopia: TQRDBText;
    QRShape9: TQRShape;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    QRLabel10: TQRLabel;
    QRLabel11: TQRLabel;
    QRLabel12: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRLabel15: TQRLabel;
    QRLabel16: TQRLabel;
    qrlDesayunoCopia: TQRLabel;
    qrlAlmuerzoCopia: TQRLabel;
    qrlComidaCopia: TQRLabel;
    qrdbDiaDesdeDesayunoCopia: TQRDBText;
    qrdbDiaDesdeAlmuerzoCopia: TQRDBText;
    qrdbDiaDesdeComidaCopia: TQRDBText;
    qrdbMesdesdeDesayunoCopia: TQRDBText;
    qrdbMesDesdeAlmuerzoCopia: TQRDBText;
    qrdbMesDesdeComidaCopia: TQRDBText;
    qrdbDiaHastaDesayunoCopia: TQRDBText;
    qrdbDiaHastaAlmuerzoCopia: TQRDBText;
    qrdbDiaHastaComidaCopia: TQRDBText;
    qrdbMesHastaDesayunoCopia: TQRDBText;
    qrdbMesHastaAlmuerzoCopia: TQRDBText;
    qrdbMesHastaComidaCopia: TQRDBText;
    qrdbAnhoDesayunoCopia: TQRDBText;
    qrdbAnhoAlmuerzoCopia: TQRDBText;
    qrdbAnhoComidaCopia: TQRDBText;
    QRLabel20: TQRLabel;
    qrlPeajeCopia: TQRLabel;
    qrlParqueoCopia: TQRLabel;
    qrlgasolinaCopia: TQRLabel;
    qrlPasajeCopia: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel26: TQRLabel;
    QRLabel27: TQRLabel;
    QRLabel28: TQRLabel;
    QRLabel29: TQRLabel;
    QRLabel30: TQRLabel;
    qrdbValorPeajeCopia: TQRDBText;
    qrdbValorParqueoCopia: TQRDBText;
    qrdbValorGasolinaCopia: TQRDBText;
    qrdbValorPasajesCopia: TQRDBText;
    qrdbFechaPeajeCopia: TQRDBText;
    qrdbFechaParqueoCopia: TQRDBText;
    qrdbFechaGasolinaCopia: TQRDBText;
    qrdbFechaPasajesCopia: TQRDBText;
    QRLabel31: TQRLabel;
    QRShape10: TQRShape;
    QRLabel32: TQRLabel;
    QRLabel33: TQRLabel;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRLabel34: TQRLabel;
    qrdbCuentaContableCopia: TQRDBText;
    qrdbAuxiliarCopia: TQRDBText;
    qrdbCentroCostoCopia: TQRDBText;
    qrdbAreaResponsabilidadCopia: TQRDBText;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRLabel35: TQRLabel;
    QRLabel36: TQRLabel;
    QRLabel37: TQRLabel;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRLabel38: TQRLabel;
    QRLabel52: TQRLabel;
    qrdbFechaPagoCopia: TQRDBText;
    qrdbValorDesayunoCopia: TQRDBText;
    qrdbValorAlmuerzoCopia: TQRDBText;
    qrdbValorComidaCopia: TQRDBText;
    qrdbTotalAlimentacionCopia: TQRDBText;
    qrdbTotalAuxilioCopia: TQRDBText;
    QRLabel53: TQRLabel;
    qrdbTotalOtrosGastosCopia: TQRDBText;
    qrdbCantidadDesayunoCopia: TQRDBText;
    qrdbCantidadAlmuerzoCopia: TQRDBText;
    qrdbCantidadComidaCopia: TQRDBText;
    qrdbCedulaFirmaCopia: TQRDBText;
    QRShape22: TQRShape;
    QRDBImage2: TQRDBImage;
    QRImage1: TQRImage;
    QRLabel54: TQRLabel;
    QRLabel56: TQRLabel;
    QRLabel57: TQRLabel;
    QRDBText43: TQRDBText;
    qrdbCiaCopia: TQRDBText;
    procedure QuickRepAfterPreview(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  FQRAuxilios: TFQRAuxilios;

implementation

{$R *.DFM}

procedure TFQRAuxilios.QuickRepAfterPreview(Sender: TObject);
begin
  Close;
end;

procedure TFQRAuxilios.FormClose(Sender: TObject;
  var Action: TCloseAction);
begin
  Action:=CaFree;
end;

end.
